### PR TITLE
Add battery text option

### PR DESCRIPTION
**Pull request by Memphiz**
This adds the option to show or hide the battery percentage text right of the battery icon.

This is untested aswell and needs review. I am uncertain if the eepromversion was meant to be incremented by 1 on each option format change.

### CODE REVIEW

**Comment by Dvogonen** [comment]
I have reviewed the code for the battery percentage display, which looks good. Ought to work without changes. 
One issue is however that at least the drawRightInfoLine functions will need tweaking.  There is simply no room to the right of the battery symbol. This means that the battery percentage is drawn outside of the screen( or to the left side on the next row)..
You were completely right to increase the EEPROM version. This has to happen each time an option is added. The display is in NTSC mode when it is started and whenever it locks into an NTSC channel.

**Comment by Memphiz** [comment]
I will look into it next week or so :) - thx for the review

**Comment by Memphiz** [comment]
I have updated the pull request with a cleaned up version where the drawing of battery with and without text is fixed in all spots. (tested with the actual device).

**Comment by Dvogonen** [comment]
OK, I am merging the pull request.
Solves #13

**Pull request merged**
